services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=ferryjoy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vbnm24680!

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
