CREATE TABLE IF NOT EXISTS "vessel_locations_by_minute" (
	"id" serial PRIMARY KEY NOT NULL,
	"vessel_id" integer NOT NULL,
	"vessel_name" text NOT NULL,
	"depart_term_id" integer NOT NULL,
	"depart_term_name" text NOT NULL,
	"depart_term_abrv" text NOT NULL,
	"arriv_term_id" integer,
	"arriv_term_name" text,
	"arriv_term_abrv" text,
	"lat" real NOT NULL,
	"lon" real NOT NULL,
	"speed" real NOT NULL,
	"heading" integer NOT NULL,
	"in_service" boolean NOT NULL,
	"at_dock" boolean NOT NULL,
	"left_dock" timestamp,
	"eta" timestamp,
	"sched_departure" timestamp,
	"op_route_abrv" text,
	"vessel_pos_num" integer,
	"time_stamp" timestamp NOT NULL,
	"time_fetched" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vessel_locations_by_second" (
	"id" serial PRIMARY KEY NOT NULL,
	"vessel_id" integer NOT NULL,
	"vessel_name" text NOT NULL,
	"depart_term_id" integer NOT NULL,
	"depart_term_name" text NOT NULL,
	"depart_term_abrv" text NOT NULL,
	"arriv_term_id" integer,
	"arriv_term_name" text,
	"arriv_term_abrv" text,
	"lat" real NOT NULL,
	"lon" real NOT NULL,
	"speed" real NOT NULL,
	"heading" integer NOT NULL,
	"in_service" boolean NOT NULL,
	"at_dock" boolean NOT NULL,
	"left_dock" timestamp,
	"eta" timestamp,
	"sched_departure" timestamp,
	"op_route_abrv" text,
	"vessel_pos_num" integer,
	"time_stamp" timestamp NOT NULL,
	"time_fetched" timestamp NOT NULL
);
